version: "3"
services:
 node:
  build: 
     context: .
  networks:
    - DbNet
    - default
  ports:
    - "2000:2000"   # P2P
    - "2100:2100"   # API
  environment:
    dbServer: database
  depends_on: 
      - database
    
 database:
  image: mongo
  restart: always
  networks:
    - DbNet


networks: 
  DbNet:
    internal: true
 