version: "3"
services:
 server:
  build: 
     context: .
  networks:
    - DbNet
    - default
  ports:
    - "2000:2000"   # P2P
    - "9000:9000"   # API
    - "9229:9229"   # NodeJS Debug
  environment:
    dbServer: database
  depends_on: 
      - database
    
 database:
  image: mongo
  restart: always
  networks:
    - DbNet


networks: 
  DbNet:
    internal: true
 